name: Deploy editor to GitHub Pages

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v7
      - name: 'Install Node'
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - name: 'Install Rust'
        uses: dtolnay/rust-toolchain@stable
      - name: 'Install wasm-pack'
        run: cargo install wasm-pack --version 0.15.0 --locked
      - name: 'Setup Pages'
        uses: actions/configure-pages@v6
      - name: 'Install node dependencies'
        run: npm ci --prefer-offline
      - name: 'Test Pages build helper'
        run: npm run test-build-editor-pages-script
      - name: 'Build editor'
        run: npm run build-editor-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'dist/apps/editor/browser'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
